[package]
name = "simplefield"
version = "0.1.0"
edition = "2024"

[dependencies]
# -- math --------------------------------------------------------------------
# struct_extractors = { version = "0.1.0", path = "../struct_extractors" }
struct_extractors = { version = "0.1.0", git = "https://github.com/witold-k/struct_extractors", rev = "8e769e7ee7dfbf447ef5e3a768bd6b666d09334b" }
# lineariterator = { version = "0.1.0", path = "../lineariterator" }
lineariterator = { version = "0.1.0", git = "https://github.com/witold-k/lineariterator.git", rev = "4ab7a6eb620b85ecff6b872b9879960a8b713bfe" }

